### ISSUE TITLE
Massive issue

### ISSUE THREAD

**Issue by SunburntRock89** [austinhuang0131/metagon#1]
* Platform: 
WINDOWS
* Category: 
Suggestion

## Description

The bot is written in 1 file and is using var.
Please fix.

### Steps to Reproduce

1: Open GitHub
2: Find this Repo
3: Open index.js

**Comment by austinhuang0131** [comment]
YOU HAVE NOT EVEN USED IT

the bot is written in dialogs and Microsoft doesn't give me a method to load dialogs 1 by 1, at least I've never seen one such example
